name: zazuberlin/c1b-display-headline
typeName: zazuberlin_c1bdisplayheadline
group: default
prefixFields: true
prefixType: full
fields:

  - identifier: header
    label: Schmuck Überschrift
    useExistingField: true

  - identifier: toggle
    label: blaue Linie am Ende ja/nein
    type: Checkbox
    renderType: checkboxToggle
    default: 1
