name: zazuberlin/c29-image-text-below-two-col
typeName: zazuberlin_c29imagetextbelowtwocol
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: imageL
    label: Image left column
    type: File
    extendedPalette: false
    minitems: 1
    maxitems: 1
    allowed: jpg, jpeg, png, gif, svg
    crop: true

  - identifier: textareaL
    type: Textarea
    label: Text links
    description: 'Text links'
    enableRichtext: true
    richtextConfiguration: zazu
    rows: 40

  - identifier: linkL
    type: Link
    label: Link left
    description: 'TypoLink (page/external/mail/url) for left column'
    required: false
    default: ''

  - identifier: linktextL
    type: Text
    label: Link text left
    description: 'Text des linken Links'

  - identifier: imageR
    label: Image right column
    type: File
    extendedPalette: false
    minitems: 1
    maxitems: 1
    allowed: jpg, jpeg, png, gif, svg
    crop: true

  - identifier: textareaR
    type: Textarea
    label: Text rechts
    description: 'Text rechts'
    enableRichtext: true
    richtextConfiguration: full
    rows: 40
  
  - identifier: linkR
    type: Link
    label: Link right
    description: 'TypoLink (page/external/mail/url) for right column'
    required: false
    default: ''

  - identifier: linktextR
    type: Text
    label: Link text right
    description: 'Text des rechten Links'