name: zazuberlin/c101-osm-map
typeName: zazuberlin_c101osmmap
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: longiCenter
    type: Text
    label: Longitude East Center
    description: 'Longitude for the center of the map e.g. 13.404954'

  - identifier: latiCenter
    type: Text
    label: Latitude North Center
    description: 'Latitude for the center of the map e.g. 52.520008'

  - identifier: longi1
    type: Text
    label: Longitude East Spot 1
    description: 'Longitude of the first spot e.group. 13.404954 '

  - identifier: lati1
    type: Text
    label: Latitude Noth Spot 1
    description: 'Latitude of the first spot e.g. 52.520008'

  - identifier: longi2
    type: Text
    label: Longitude East Spot 2
    description: 'Longitude of the second spot e.g. 13.404954 '
    
  - identifier: lati2
    type: Text
    label: Latitude Noth Spot 2
    description: 'Latitude of the second spot e.g. 52.520008 '


