base: 'https://bsggera.ddev.site/'
dependencies:
  - typo3/fluid-styled-content
  - zazuberlin/zazuset1
  - typo3/form
  - typo3/seo-sitemap
  - georgringer/news
languages:
  -
    title: Deutsch
    enabled: true
    locale: de_DE.utf8
    hreflang: de-DE
    base: /
    websiteTitle: ''
    navigationTitle: Deutsch
    flag: de
    languageId: 0
rootPageId: 26
websiteTitle: ''
