name: zazuberlin/c22-num-text-image
typeName: zazuberlin_c22numtextimage
group: default
prefixFields: true
prefixType: full
fields:

  - identifier: number
    type: Number
    label: Number
    description: 'Nummernfeld linke Spalte'

  - identifier: textarea
    type: Textarea
    label: Text left
    description: 'Text linke Spalte'
    enableRichtext: true
    richtextConfiguration: zazu
    rows: 40

  - identifier: image
    useExistingField: true
    label: Image
    type: File
    extendedPalette: false
    minitems: 1
    maxitems: 1
    allowed: jpg, jpeg, png, gif, svg
    description: 'Bild linke Spalte.'

  - identifier: toggle
    label: blaue Linie am Ende ja/nein
    type: Checkbox
    renderType: checkboxToggle
    default: 0


    