name: nobrain/s2s5-two-column-text-list
typeName: nobrain_s2s5twocolumntextlist
group: default
prefixFields: true
prefixType: full
fields:
  
  - identifier: header
    label: Überschrift über uns
    useExistingField: true

  - identifier: header2
    type: Textarea
    label: Überschrift Mitglieder
    useExistingField: false

  - identifier: toggle
    label: Überschrift über uns ja/nein
    type: Checkbox
    renderType: checkboxToggle
    default: 0

  - identifier: toggle2
    label: Überschrift Mitglieder ja/nein
    type: Checkbox
    renderType: checkboxToggle
    default: 0  

  - identifier: toggle3
    label: Hintergrundbild ja/nein
    type: Checkbox
    renderType: checkboxToggle
    default: 0

  - identifier: textarea
    type: Textarea
    label: Text links
    description: 'Text links'
    enableRichtext: true
    richtextConfiguration: zazu
    rows: 40

  - identifier: listItems
    type: Collection
    label: List Items
    labelField: text
    fields:
      - identifier: text
        type: Text
        default: 'Default value'
        min: 2
        max: 50
        required: true