name: nobrain/s1s1-hero
typeName: nobrain_s1s1hero
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    label: Hero Überschrift
    useExistingField: true

  - identifier: header2
    type: Textarea
    label: Unterüberschrift
    description: 'Die Unterüberschrift im Hero'
    enableRichtext: false
    rows: 1

  - identifier: listItems
    type: Collection
    label: Buttons
    description: 'Beliebig viele Buttons (Text + Link)'
    minItems: 0
    maxItems: 50
    fields:
    - identifier: link
      type: Link
      label: Link at the end
      description: 'TypoLink (page/external/mail/url) for the link at the end'
      required: false
      default: ''
    - identifier: linktext
      type: Text
      label: Link text 
      description: 'Text des unteren Links'




