name: nobrain/s1s1-hero
typeName: nobrain_s1s1hero
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    label: Hero Überschrift
    useExistingField: true

  - identifier: header2
    type: Textarea
    label: Unterüberschrift
    description: 'Die Unterüberschrift im Hero'
    enableRichtext: false
    rows: 1


