name: nobrain/titel-video
typeName: nobrain_titelvideo
group: default
prefixFields: true
prefixType: full
fields:
  - identifier: header
    label: Überschrift
    useExistingField: true

  - identifier: toggle
    label: Überschrift anzeigen?
    type: Checkbox
    renderType: checkboxToggle
    default: 1

  - identifier: media
    type: File
    label: Medien (Bild oder Video)
    allowed: 'jpg,jpeg,png,webp,mp4'
    maxItems: 1

  - identifier: toggle3
    label: Hintergrundbild sichtbar
    type: Checkbox
    renderType: checkboxToggle
    default: 0