name: zazuberlin/c28-two-column-list
label: Two Column List
typeName: zazuberlin_c28twocolumnlist
description: A content element with a two column list.
group: default
prefixFields: true
prefixType: full
fields:
  -
    identifier: header
    useExistingField: true
  - identifier: listItems
    type: Collection
    label: List Items
    labelField: text
    fields:
      - identifier: text
        type: Textarea
        label: Text content
        rows: 5
  - identifier: link
    type: Link
    label: Link at the end
    description: 'TypoLink (page/external/mail/url) for the link at the end'
    required: false
    default: ''
  - identifier: linktext
    type: Text
    label: Link text 
    description: 'Text des unteren Links'


