name: zazuberlin/c17-flexslider
typeName: zazuberlin_c17flexslider
group: default
prefixFields: true
vendorPrefix: tx_bsggerapackage
fields:
  - identifier: image
    useExistingField: true
    label: Image
    type: File
    extendedPalette: false
    minitems: 1
    allowed: jpg, jpeg, png, gif, svg
  - identifier: header
    useExistingField: true
    label: Header
    type: Text
    extendedPalette: false
    minitems: 1
    maxitems: 1
    description: 'Eine versteckte Überschrift für SEO.'
